### ISSUE TITLE
The uloop.interval example does not work `Type error: left-hand side is not a function`

### ISSUE THREAD

**Issue by feckert** [jow-/ucode#273]
I want to deal with ucode and have come across the following error.

The [example](https://ucode.mein.io/module-uloop.html#interval) does not work either.
The same error is shown.

Code
```
#!/usr/bin/ucode -S

'use strict';

import * as uloop from 'uloop';

let nmea = {
        get: function () {
                printf("Interval callback executed!\n");
        }
};

uloop.init();
uloop.interval(1000,nmea.get);
uloop.run();
```
Error message:
```
root@LUKE-C-P094 ~ # ./mm-gps 
Type error: left-hand side is not a function
In ./mm-gps, line 14, byte 32:

 `uloop.interval( 1000, nmea.get );`
  Near here ---------------------^

```
Now I don't know if I'm doing something wrong.

**Comment by IdWV** [comment]
The existence of uloop.interval is dependent on the macro HAVE_ULOOP_INTERVAL being set compile time, which AFAICS is set when libuloop has a function uloop_interval_set. Don't know why it would or wouldn't have that.

Anyway, you can easily see if that function is available:
```
import * as uloop from 'uloop';
print( uloop )
```

**Comment by sebastianertz** [comment]
For pretty print: 

``` javascript
import * as uloop from 'uloop';
printf("%.J\n",uloop);
````

**Comment by feckert** [comment]
Thanks for your hint.
I am working on openwrt-23.05 and the function `uloop.interval` is not available in `libubox` for this openwrt branch, because the version of `libubox` is too old in this branch. The functionality was added with commit https://github.com/openwrt/libubox/commit/82fa6480de7a85d0ced0701ab7c8825e31b90770 and in openwrt-23.05  the `libubox` version is at commit https://github.com/openwrt/libubox/commit/75a3b870cace1171faf57bd55e5a9a2f1564f757.
